// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseNotesDir():Promise<main.WorkspaceState>;

export function CreateFile(arg1:string,arg2:string):Promise<string>;

export function CreateFolder(arg1:string,arg2:string):Promise<string>;

export function DeletePath(arg1:string):Promise<void>;

export function ExportRecoveryKey():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportRecoveryKey(arg1:string):Promise<main.WorkspaceState>;

export function InitWorkspace():Promise<main.WorkspaceState>;

export function LoadNote(arg1:string,arg2:string):Promise<main.NoteDocument>;

export function ReencryptNotes(arg1:string,arg2:string):Promise<main.ReencryptResult>;

export function RefreshWorkspace():Promise<main.WorkspaceState>;

export function RenamePath(arg1:string,arg2:string):Promise<string>;

export function SaveNote(arg1:string,arg2:Array<main.Block>,arg3:string,arg4:boolean):Promise<void>;

export function SetupGeneratedKey():Promise<main.WorkspaceState>;

export function SetupManualPassphrase():Promise<main.WorkspaceState>;
