// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseNotesDir() {
  return window['go']['main']['App']['ChooseNotesDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitWorkspace() {
  return window['go']['main']['App']['InitWorkspace']();
}

export function LoadNote(arg1, arg2) {
  return window['go']['main']['App']['LoadNote'](arg1, arg2);
}

export function RefreshWorkspace() {
  return window['go']['main']['App']['RefreshWorkspace']();
}

export function SaveNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2, arg3, arg4);
}
