// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LoadNote(arg1:string,arg2:string):Promise<Array<main.Block>>;

export function SaveNote(arg1:string,arg2:Array<main.Block>,arg3:string):Promise<void>;
